export const catalog = [
  { 
    id: 's-1', 
    name: 'Baby Care', 
    category: 'Care', 
    price: 799.0, 
    durationText: '6 Hours', 
    packageText: 'Daily Needs', 
    imageUrl: '/services/babycare.webp', 
    desc: 'Professional baby care support at home by trained and verified caregivers. Safe, responsible, and caring service for infants and children with trusted assistance for daily needs.', 
    details: ['Safe, caring support for daily needs', 'Feeding, diapers, interactive playtime', 'Double-vetted professional caregivers', 'Flexible 6-hour slot shifts'],
    workerName: 'Prabha M.',
    workerAvatar: null,
    workerRole: 'Certified Nanny'
  },
  { 
    id: 's-2', 
    name: 'Full House Deep Cleaning', 
    category: 'Cleaning', 
    price: 3499.0, 
    durationText: '5-6 Hours', 
    packageText: 'Deep Hygiene', 
    imageUrl: '/services/housecleaning.webp', 
    desc: 'Complete deep cleaning service for the entire home including living room, bedrooms, kitchen, and bathroom. Professional equipment used for premium hygiene and spotless results.', 
    details: ['Sanitation of bathrooms, sink, tiles', 'Deep vacuuming of sofa, carpets, beds', 'Floor scrubbing and dust extraction', 'Hygienic eco-friendly solutions'],
    workerName: 'Shweta K.',
    workerAvatar: null,
    workerRole: 'Lead Sanitation Pro'
  },
  { 
    id: 's-3', 
    name: 'Bathroom Deep Cleaning', 
    category: 'Cleaning', 
    price: 749.0, 
    durationText: '1.5 Hours', 
    packageText: 'Premium Sanitation', 
    imageUrl: '/services/bathroom-cleaning.webp', 
    desc: 'Deep sanitation and premium cleaning including tiles, fittings, mirrors, sinks, and floor cleaning with hygienic professional solutions for complete bathroom hygiene.', 
    details: ['Complete stain and scale removal', 'Sanitizing of toilet seat & flush bowl', 'Mirrors, taps, and exhaust deep wash', 'Disinfection of floor tiles and drains'],
    workerName: 'Deepak S.',
    workerAvatar: null,
    workerRole: 'Sanitation Expert'
  },
  { 
    id: 's-4', 
    name: 'Full Kitchen Cleaning', 
    category: 'Cleaning', 
    price: 499.0, 
    durationText: '2 Hours', 
    packageText: 'Fresh Kitchen', 
    imageUrl: '/services/kitchen-cleaning.webp', 
    desc: 'Complete kitchen cleaning including slabs, shelves, sink area, stove cleaning, and hygienic surface treatment for a fresh and organized cooking space.', 
    details: ['Stove, burners, and grid degreasing', 'Exterior cabinet and counter scrub', 'Stainless steel sink scale clearing', 'Exhaust fan and chimney surface wipe'],
    workerName: 'Nisha R.',
    workerAvatar: null,
    workerRole: 'Kitchen Hygiene Pro'
  },
  { 
    id: 's-5', 
    name: 'Dust Cleaning', 
    category: 'Cleaning', 
    price: 149.0, 
    durationText: '1 Hour', 
    packageText: 'Quick Dusting', 
    imageUrl: '/services/dust-cleaning.webp', 
    desc: 'Quick and effective dust removal for furniture, electronics, shelves, windows, and home interiors to maintain a consistently fresh and clean environment.', 
    details: ['Dry and wet wiping of home furniture', 'Dusting of television, speakers, consoles', 'Wiping of window glass panes', 'Complete floor sweeping and dry mopping'],
    workerName: 'Anjali P.',
    workerAvatar: null,
    workerRole: 'Dust Extraction Pro'
  },
  { 
    id: 's-6', 
    name: 'House Shifting', 
    category: 'Shifting', 
    price: 3499.0, 
    durationText: '1 Day', 
    packageText: '2BHK Package', 
    imageUrl: '/services/house-shifting.webp', 
    desc: 'Professional packing and shifting service for safe home relocation with trained staff, careful handling of furniture, appliances, and all household items.', 
    details: ['Multi-layer bubble wrap & heavy box packing', 'Safe loading and unloading in transport', 'Careful transit of sofas, beds, appliances', 'Dismantling and reassembly support'],
    workerName: 'Rajesh Crew',
    workerAvatar: null,
    workerRole: 'Elite Movers'
  },
  { 
    id: 's-7', 
    name: 'Cooking Service', 
    category: 'Cooking', 
    price: 149.0, 
    durationText: '1 Hour', 
    packageText: 'Meal Prep', 
    imageUrl: '/services/cooking-service.webp', 
    desc: 'Professional home cooking support with hygienic preparation, kitchen assistance, and fresh meal service by trained and experienced home service professionals.', 
    details: ['Hygienic fresh meal preparation', 'North & South Indian menu options', 'Pre-cooking vegetable chopping support', 'Kitchen space cleanup after prep'],
    workerName: 'Ramesh H.',
    workerAvatar: null,
    workerRole: 'Certified Executive Chef'
  },
  { 
    id: 's-8', 
    name: 'House Painting', 
    category: 'Painting', 
    price: 20099.0, 
    durationText: '2-3 Days', 
    packageText: 'All Materials Included', 
    imageUrl: '/services/house-painting.webp', 
    desc: 'Premium house painting service for interiors and exteriors with all materials included. Smooth finish, quality workmanship, and professional painters for beautiful lasting results.', 
    details: ['Wall sanding and wall putty application', 'Double coat premium plastic emulsion', '2BHK: Rs. 20,099 \| 3BHK: Rs. 23,499 options', 'Masking tape security protection for furniture'],
    workerName: 'Vikram S.',
    workerAvatar: null,
    workerRole: 'Elite Wall Stylist'
  },
  { 
    id: 's-9', 
    name: 'Electrician Service', 
    category: 'Technical', 
    price: 499.0, 
    durationText: '1 Hour', 
    packageText: 'Essential Repairs', 
    imageUrl: '/services/electrician.webp', 
    desc: 'Professional electrician support for repairs, installations, switchboards, wiring, fan fitting, lighting solutions, and all essential home electrical services.', 
    details: ['Switchboard, socket, and wiring repairs', 'Ceiling fan & light fitting installs', 'Circuit breaker checks and diagnostics', 'Strict compliance with electric safety code'],
    workerName: 'Kiran R.',
    workerAvatar: null,
    workerRole: 'Certified Wireman'
  },
  { 
    id: 's-10', 
    name: 'Security Provider', 
    category: 'Care', 
    price: 899.0, 
    durationText: '8 Hours', 
    packageText: 'Safe Protection', 
    imageUrl: '/services/security-provider-v2.webp', 
    desc: 'Trained and verified security personnel for homes, apartments, offices, and events. Reliable protection with professional discipline and complete safety assurance.', 
    details: ['Double-vetted background checks', 'Uniformed guard on alert for 8 hours', 'Visitor registry gate tracking', 'Security patrols around parameters'],
    workerName: 'Dharma J.',
    workerAvatar: null,
    workerRole: 'Police-Vetted Guard'
  },
  { 
    id: 's-11', 
    name: 'Pest Control', 
    category: 'Cleaning', 
    price: 2599.0, 
    durationText: '2 Hours', 
    packageText: '2BHK Package', 
    imageUrl: '/services/pest-control-v2.webp', 
    desc: 'Professional pest control treatment for cockroaches, insects, termites, and unwanted pests using safe and effective solutions for a clean and hygienic home.', 
    details: ['Odorless gel and spray injections', 'Cockroach, ant, and spider control', 'Drain pipe spray sanitation', 'Safe, eco-friendly, and odorless sprays'],
    workerName: 'Praveen L.',
    workerAvatar: null,
    workerRole: 'Chemical Safety Pro'
  }
];
